version: '3.3'
services:
  apachephp:
    container_name: ${projectname}_apachephp
    image: ${docker_registry}/${docker_user}/${docker_project}/${docker_php_name}:latest
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${GID}
      - APP_URL=${url}
    working_dir: /var/www/html
    ports:
      - ${extport}:${innerport}
    volumes:
      - ../src:/var/www/html
      - ../logs:/var/log
    networks:
      - projectnetwork
  mysql:
    container_name: ${projectname}_mysql
    image: ${docker_registry}/${docker_user}/${docker_project}/${docker_mysql_name}:latest
    environment: 
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_OUTPORT=${MYSQL_OUTPORT}
    ports:
      - "${MYSQL_OUTPORT}:3306"
    volumes:
      - ./db/SQLScript:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - projectnetwork
networks:
  projectnetwork:
    driver: bridge